### ISSUE TITLE
Computed Macros

### ISSUE THREAD

**Issue by hedgerh** [gabeklein/expressive-mvc#41]
Something I really like about Ember is that it provides "computed property macros," which are shorter ways to express common types of computed property.  For example,

```
{
  age: 24,
  isAdult: gte('age', 18),

  job: 'Engineer',
  isEngineer: equal('job', 'Engineer'),

  cats: 1,
  dogs: 2,
  numberOfPets: sum(['cats', 'dogs']),
}
```

I think these make a great developer experience, so I thought I'd mention them.  Here's the Ember docs listing all the macros they have: https://api.emberjs.com/ember/3.3/classes/@ember%2Fobject%2Fcomputed

**Comment by gabeklein** [comment]
Hey Harry, great suggestion. Believe it or not this is already possible todo, docs for it are in the works though.

This library has a concept of "instructions" which would enable what you suggested. There are a handful of built-in instructions, one of which is `from`. It works exactly the same way a getter does, but adds exactly what you'd need for a macro-concept.

```js
class 

```

**Comment by gabeklein** [comment]
Hey Harry, great suggestion. Believe it or not this is already possible todo, docs for it are in the works though.

This library has a concept of "instructions". First introduced [here](https://github.com/gabeklein/expressive-mvc#peer-consumers) in docs. There are a handful of built-in instructions, one of which is `from`. It works exactly the same way a getter does, there to cover this type of use-case.

### For example:

```js
import Model from "@expressive/mvc";

class State extends Model {
  job = 'Engineer'

  get isEngineer(){
    return this.job == "Engineer";
  }
}
```
> Is equivalent to:
```js
import Model, { from } from "@expressive/mvc";

class State extends Model {
  job = 'Engineer'

  isEngineer = from(isEngineer);
}

function isEngineer(subject){
  return subject.job == "Engineer";
}
```

<h2></h2><br/>

Why `from` exists, is to make getter-instructions extensible. Either part of a macro-library, or within your app, a `sum` macro could be implemented like this:

```js
import { from } from "@expressive/mvc";

export function sum(...keys){
  function calculateSum(subject){
    let total = 0;

    for(const key of keys)
      total += subject[key];

    return total;
  }

  return from(calculateSum);
}
```
Now use your custom-instruction on the Model!
```js
import Model from "@expressive/mvc";
import { sum } from "./macros";

class State extends Model {
  cats = 1;
  dogs = 2;

  numberOfPets = sum("cats", "dogs");
}
```

And there you go, an easy purpose-built macro you control. 👌
